---
-
  name: this playbook is for my web server
  hosts: localhost
 
  tasks:
  -
    name: installing appache package
    package:
      name: httpd
      state: present
  -
    name: configuring apache files
    file:
      path: "/var/www/html/index.html"
      state: touch
  -
    name: customizing file
    copy:
      dest: "/var/www/html/index.html"
      content: "<h1>Hello Ajinkya</h1>"
  -
    name: starting Web server
    service:
      name: httpd
      state: started
